### ISSUE TITLE
Exception AttributeError when running XGBoostSageMakerEstimator on a Sagemaker Notebook Instance connected to an EMR spark cluster

### ISSUE THREAD

**Issue by pythonmath** [aws/sagemaker-spark#104]
### System Information
EMR Release label: emr-5.27.0
Hadoop distribution: Amazon 2.8.5
Applications: Spark 2.4.4, Hive 2.3.5, Ganglia 3.7.2, Livy 0.6.0, Hue 4.4.0, TensorFlow 1.14.0
PySpark Version: python36-sagemaker-pyspark (1.2.4)
Algorithm: XGBoost
Setup: Sagemaker Notebook Instance connected to an EMR spark cluster

### Describe the problem
I am training an XGBoost model for classifying the MNIST dataset. When I try to initialize an object using the XGBoostSageMakerEstimator() constructor I get the following error:

`Exception AttributeError: "'Option' object has no attribute '_java_obj'" in <bound method Option.__del__ of <sagemaker_pyspark.wrapper.Option object at 0x7f19456a7e90>> ignored
Exception AttributeError: "'ScalaMap' object has no attribute '_java_obj'" in <bound method ScalaMap.__del__ of <sagemaker_pyspark.wrapper.ScalaMap object at 0x7f1945900290>> ignored
Exception AttributeError: "'ScalaMap' object has no attribute '_java_obj'" in <bound method ScalaMap.__del__ of <sagemaker_pyspark.wrapper.ScalaMap object at 0x7f1945900350>> ignored
Exception AttributeError: "'Option' object has no attribute '_java_obj'" in <bound method Option.__del__ of <sagemaker_pyspark.wrapper.Option object at 0x7f19456a7d90>> ignored
Exception AttributeError: "'Option' object has no attribute '_java_obj'" in <bound method Option.__del__ of <sagemaker_pyspark.wrapper.Option object at 0x7f19456a7d50>> ignored
Exception AttributeError: "'Option' object has no attribute '_java_obj'" in <bound method Option.__del__ of <sagemaker_pyspark.wrapper.Option object at 0x7f19456a7d10>> ignored
Exception AttributeError: "'Option' object has no attribute '_java_obj'" in <bound method Option.__del__ of <sagemaker_pyspark.wrapper.Option object at 0x7f19456a7cd0>> ignored
Exception AttributeError: "'Option' object has no attribute '_java_obj'" in <bound method Option.__del__ of <sagemaker_pyspark.wrapper.Option object at 0x7f19456a73d0>> ignored`

Attached is a .zip containing a screenshot of this error and the .ipynb that can be used to reproduce it.
[issue.zip](https://github.com/aws/sagemaker-spark/files/4013579/issue.zip)

Here is the screenshot for a quick look:
![image](https://user-images.githubusercontent.com/46337228/71635131-a33e8280-2bd6-11ea-9c5f-e27090cd9deb.png)

**Comment by nadiaya** [comment]
Running follow code fixed the issue for me:
```
from pyspark.sql import SparkSession
import sagemaker_pyspark

# Configure Spark to use the SageMaker Spark dependency jars
jars = sagemaker_pyspark.classpath_jars()

classpath = ":".join(sagemaker_pyspark.classpath_jars())

# See the SageMaker Spark Github repo under sagemaker-pyspark-sdk
# to learn how to connect to a remote EMR cluster running Spark from a Notebook Instance.
spark = SparkSession.builder.config("spark.driver.extraClassPath", classpath)\
    .master("local[*]").getOrCreate()
# Configure Spark to use the SageMaker Spark dependency jars
jars = sagemaker_pyspark.classpath_jars()

classpath = ":".join(sagemaker_pyspark.classpath_jars())

# See the SageMaker Spark Github repo under sagemaker-pyspark-sdk
# to learn how to connect to a remote EMR cluster running Spark from a Notebook Instance.
spark = SparkSession.builder.config("spark.driver.extraClassPath", classpath)\
    .master("local[*]").getOrCreate()
```

**Comment by nadiaya** [comment]
Full code that I ran and it worked:
```
from pyspark.sql import SparkSession
import sagemaker_pyspark

# Configure Spark to use the SageMaker Spark dependency jars
jars = sagemaker_pyspark.classpath_jars()

classpath = ":".join(sagemaker_pyspark.classpath_jars())

# See the SageMaker Spark Github repo under sagemaker-pyspark-sdk
# to learn how to connect to a remote EMR cluster running Spark from a Notebook Instance.
spark = SparkSession.builder.config("spark.driver.extraClassPath", classpath)\
    .master("local[*]").getOrCreate()
# Configure Spark to use the SageMaker Spark dependency jars
jars = sagemaker_pyspark.classpath_jars()

classpath = ":".join(sagemaker_pyspark.classpath_jars())

# See the SageMaker Spark Github repo under sagemaker-pyspark-sdk
# to learn how to connect to a remote EMR cluster running Spark from a Notebook Instance.
spark = SparkSession.builder.config("spark.driver.extraClassPath", classpath)\
    .master("local[*]").getOrCreate()
```
```
from sagemaker import get_execution_role

role = get_execution_role()
```
```
from sagemaker_pyspark.algorithms import XGBoostSageMakerEstimator
from sagemaker_pyspark import IAMRole

xgboost_estimator = XGBoostSageMakerEstimator(
    trainingInstanceType='ml.m4.xlarge',
    trainingInstanceCount=1,
    endpointInstanceType='ml.m4.xlarge',
    endpointInitialInstanceCount=1,
    sagemakerRole=IAMRole(role))
```

**Comment by nadiaya** [comment]
Notebook example that has more details about it:
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-spark/pyspark_mnist/pyspark_mnist_xgboost.ipynb

**Comment by pythonmath** [comment]
![image](https://user-images.githubusercontent.com/46337228/73313319-c19c9b80-41df-11ea-9d40-e3afc88edb0b.png)

Hi nadiaya, I tried running your posted code before creating an estimator but I still have the error.

**Comment by laurenyu** [comment]
I tried running the notebook posted (https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-spark/pyspark_mnist/pyspark_mnist_xgboost.ipynb) with a fresh Notebook Instance, and wasn't able to reproduce the error you encountered when creating an estimator.

could you try maybe restarting your notebook instance?

**Comment by pythonmath** [comment]
Fixed! The solution was that I needed to downgrade my EMR cluster to emr-5.19.1 alongside Spark version down to Spark 2.3.2.

source: [https://stackoverflow.com/questions/58105098/runtime-error-using-xgboostsagemakerestimator-from-sagemaker-pyspark-on-aws-emr](https://stackoverflow.com/questions/58105098/runtime-error-using-xgboostsagemakerestimator-from-sagemaker-pyspark-on-aws-emr)

![image](https://user-images.githubusercontent.com/46337228/75384391-e180b700-5892-11ea-8753-2f09f6712fbf.png)

**Comment by AnshumanRanjan** [comment]
For people still reporting this issue , here is what I found troubleshooting it 

a) pyspark added this fix (https://github.com/apache/spark/commit/7706eea6a8bdcd73e9dde5212368f8825e2f1801)  on Spark 2.4.0 + versions , this code implements a __del__ method to clear out Java context for GC purpose , this change has caused the Above error messages that has been reported in the ticket . Although the Exception reported is not Fetal and code should run regardless 

This exception info will be reported if you run (Estimator creation) part in separate cell  , if you put on code lines after that it will get suppressed on Juypter 

This would also appear in EMR emr-5.20.0 onwards and also EMR notebook linked to cluster with EMR version > 5.19 .
