### ISSUE TITLE
'SparkContext' object has no attribute 'read'

### ISSUE THREAD

**Issue by marami52** [aws/sagemaker-spark#11]
I just tried the K-mean clustering example on a SageMaker notebook instance but I get the above mentioned error in line:

```pyhton
training_data = spark.read.format("libsvm").option("numFeatures", "784")
  .load("s3a://sagemaker-sample-data-{}/spark/mnist/train/".format(region))
```
I defined `spark` in `local` mode as explained in the example:

```python
conf = (SparkConf()
        .set("spark.driver.extraClassPath", ":".join(classpath_jars())))
spark = SparkContext(conf=conf)
```
Do I miss something in my configuration?

**Comment by andremoeller** [comment]
Hi @marami52 ,

Thanks for using Amazon SageMaker!

Instead of using a `SparkContext`, I think we should be using a `SparkSession` to load the data into a `DataFrame`, like:

```
from pyspark.sql import SparkSession
spark = SparkSession.builder.config("spark.driver.extraClassPath", ":".join(sagemaker_pyspark.classpath_jars())).getOrCreate()
training_data = spark.read.format("libsvm").option("numFeatures", "784")
  .load("s3a://sagemaker-sample-data-{}/spark/mnist/train/".format(region))
```

We have this wrong in our docs -- I'll be sure to get this updated.

Thanks again!

**Comment by marami52** [comment]
Yes, that works. thank you!
