### ISSUE TITLE
remove use of `setup_requires`

### ISSUE THREAD

**Issue by Chichilele** [aws/sagemaker-spark#122]
Please fill out the form below.

### System Information
- **Spark or PySpark**: PySpark
- **SDK Version**: 1.3.1
- **Spark Version**: 3.0.0
- **Algorithm (e.g. KMeans)**: NA

### Describe the problem
`setup_requires` and `tests_require` are deprecated. Do not use them in `setup.py`. See deprecation warning from early 2019 https://pypi.org/project/pytest-runner/

- **Exact command to reproduce**:
pip install sagemaker-pyspark

**Comment by laurenyu** [comment]
thanks for bringing this to our attention. I've opened a PR to address this: #125
