### ISSUE TITLE
XGBoostSageMakerEstimator seed parameter should be Int

### ISSUE THREAD

**Issue by SilenyHobit** [aws/sagemaker-spark#40]
I'm running **sagemaker-spark**(1.0.4 shaded inside my jar) on **EMR**(5.12.0) cluster and I encountered an error when trying to start XGBoost training job as in [this notebook example](https://github.com/aws/sagemaker-spark/blob/master/examples/notebooks/jupyter/xgboost/MNIST-xgboost-train.ipynb):
`ClientError: Parameter seed expects integer input.`

Simply changing the seed parameter in **XGBoostSageMakerEstimator** class to Int works and the job finishes.

EDIT: Forgot to mention I'm actually setting the parameter to 0 (default value).

**Comment by ChoiByungWook** [comment]
Hello,

Thanks for bringing this issue to our attention.

We are working towards a fix.

Thanks!

**Comment by ChoiByungWook** [comment]
We have merged this fix and will let you know when this is released.

Thanks!

**Comment by ChoiByungWook** [comment]
The fix has been released and should show up in maven central as 1.0.5.
