### ISSUE TITLE
SageMakerModel.fromModelS3Path() returns exception when loading a model saved in SageMaker

### ISSUE THREAD

**Issue by haowang-ms89** [aws/sagemaker-spark#52]
Hi,
I write my python code with Zeppelin 0.7.3 and Spark 2.3.0 on an EMR (emr-5.13.0) cluster to use SageMaker's XGBoost algorithm. Everything is fine when I predict with a just-trained model. However, when I try to load a model saved in SageMaker with:
`saved_model = SageMakerModel.fromModelS3Path(`
    `modelPath = "s3://000-sagemaker-us-west-2/4a2666a0-4eeb-423d-a1b9-47a8f9acfad5/trainingJob-3230c8decba9-2018-05-30T03-21-53-138/trainingJob-3230c8decba9-2018-05-30T03-21-53-138/output/model.tar.gz",`
    `modelExecutionRoleARN = "arn:aws:iam::000:role/service-role/AmazonSageMaker-ExecutionRole-20180427T160487",`
    `modelImage = "433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:1",`
    `endpointInstanceType = "ml.c4.xlarge",`
    `endpointInitialInstanceCount = 1,`
    `requestRowSerializer = serializers.UnlabeledCSVRequestRowSerializer(),`
    `responseRowDeserializer = deserializers.XGBoostCSVRowDeserializer()`
    `)`

The following exception returns:
`Traceback (most recent call last):`
  `File "/tmp/zeppelin_pyspark-8937101077514807987.py", line 367, in <module>`
`Exception: Traceback (most recent call last):`
  `File "/tmp/zeppelin_pyspark-8937101077514807987.py", line 355, in <module>`
  `File "<stdin>", line 1, in <module>`
  `File "/usr/lib/spark/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1151, in __call__`
    `args_command, temp_args = self._build_args(*args)`
  `File "/usr/lib/spark/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1121, in _build_args`
    `[get_command_part(arg, self.pool) for arg in new_args])`
  `File "/usr/lib/spark/python/lib/py4j-0.10.6-src.zip/py4j/protocol.py", line 290, in get_command_part`
    `command_part = REFERENCE_TYPE + parameter._get_object_id()`
  `File "/usr/lib/spark/python/pyspark/sql/dataframe.py", line 1182, in __getattr__`
    `"'%s' object has no attribute '%s'" % (self.__class__.__name__, name))`
`AttributeError: 'DataFrame' object has no attribute '_get_object_id'`

I see a similar issue here: [https://github.com/aws/sagemaker-spark/issues/34](url) but do not know how to apply the workaround provided. Thanks for help!

**Comment by laurenyu** [comment]
hi @haowang-ms89, what version of the SDK are you using? Also, could you post/share your entire training script?

**Comment by haowang-ms89** [comment]
Hi @laurenyu ,
I updated the SDKs to: py4j-0.10.7, pyspark-2.3.1, sagemaker-pyspark-1.1.1 and the problem is gone now. Thanks for your help!
