### ISSUE TITLE
Incorrect description for XGBoost parameter 'max_depth'

### ISSUE THREAD

**Issue by EvanzzzZ** [aws/sagemaker-spark#56]
Please fill out the form below.

### System Information
- **Spark or PySpark**: pyspark
- **SDK Version**:
- **Spark Version**:
- **Algorithm (e.g. KMeans)**: XGBoost

### Describe the problem
Description for 'max_depth' is incorrect.

https://github.com/aws/sagemaker-spark/blob/master/sagemaker-pyspark-sdk/src/sagemaker_pyspark/algorithms/XGBoostSageMakerEstimator.py#L136

See
https://docs.aws.amazon.com/sagemaker/latest/dg/xgboost_hyperparameters.html

### Minimal repo / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- **Exact command to reproduce**:

**Comment by nadiaya** [comment]
Thank you for reporting this. I've create a pull request to fix it.

**Comment by yangaws** [comment]
PR merged.
