### ISSUE TITLE
No way to use Spark with Deep AR

### ISSUE THREAD

**Issue by glyfnet** [aws/sagemaker-spark#59]
Please fill out the form below.

### System Information
- **Spark or PySpark**: PySpark
- **SDK Version**:  latest
- **Spark Version**: latest
- **Algorithm (e.g. KMeans)**: DeepAR

### Describe the problem
There is no request row deserialiser defined for the deep AR algorithm, and not very good documentation on how to create one.  

### Minimal repo / logs

- **Exact command to reproduce**:
# Create an Estimator from scratch
estimator = SageMakerEstimator(
    trainingImage = ecr, # Training image 
    modelImage = ecr, # Model image
    requestRowSerializer = ProtobufRequestRowSerializer(),
    responseRowDeserializer = ProtobufResponseRowDeserializer(???HOW TO SPECIFY SCHEMA????),
    hyperParameters = {
        "time_freq": "min", 
        "prediction_length": "30",
        "context_length": "30",
        "likelihood": "gaussian",
        "epochs": 10,
        "mini_batch_size": 100,
        "early_stopping_patience": 3
    }, # Set parameters deep ar
    sagemakerRole = IAMRole(role),
    trainingInstanceType = "ml.m4.xlarge",
    trainingInstanceCount = 1,
    endpointInstanceType = "ml.t2.medium",
    endpointInitialInstanceCount = 1,
    trainingSparkDataFormat = "parquet",
    namePolicyFactory = RandomNamePolicyFactory("sparksm-4-"),
    endpointCreationPolicy = EndpointCreationPolicy.CREATE_ON_TRANSFORM
)

**Comment by andremoeller** [comment]
Hi @glyfnet 

The DeepAR documentation says that DeepAR takes JSON for requests and returns JSON responses.

https://docs.aws.amazon.com/sagemaker/latest/dg/deepar-in-formats.html

You'd have to serialize rows so that requests match that input format, and deserialize responses back into a DataFrame with a schema following the response format.

**Comment by andremoeller** [comment]
Hi @glyfnet ,

I'm going to close this issue, but please feel free to reopen it if you have more questions. Thanks!

**Comment by advanisunny3** [comment]
Apologies for commenting on closed issue. @glyfnet did you get it working for DeepAR algorithm? I am also looking to use spark to create DeepAR estimator. Any help would be much appreciated.
