### ISSUE TITLE
[feature request] matrix features?

### ISSUE THREAD

**Issue by yifeim** [aws/sagemaker-spark#63]
### System Information
- **Spark or PySpark**: PySpark
- **SDK Version**: sagemaker-pyspark==1.1.3
- **Spark Version**: pyspark==2.3.1
- **Algorithm (e.g. KMeans)**: save to recordio

### Describe the problem
We were creating recordio using `df.write.format('sagemaker').save`. The sagemaker document suggests possibility for storing matrices as feature types (https://docs.aws.amazon.com/sagemaker/latest/dg/cdf-training.html). This is particularly useful for us since we have multiple feature groups and would hope to separate them. In other words, we would like to save "an optional shape that allows the vector to represent a matrix".

Taking one step further, is it possible to do sparse matrices?

Excerpt from sagemaker common data types - training:

```
// A sparse or dense rank-R tensor that stores data as doubles (float64).
 message Float32Tensor   {
     // Each value in the vector. If keys is empty, this is treated as a
     // dense vector.
     repeated float values = 1 [packed = true];
 
     // If key is not empty, the vector is treated as sparse, with
     // each key specifying the location of the value in the sparse vector.
     repeated uint64 keys = 2 [packed = true];
 
     // An optional shape that allows the vector to represent a matrix.
     // For example, if shape = [ 10, 20 ], floor(keys[i] / 10) gives the row,
     // and keys[i] % 20 gives the column.
     // This also supports n-dimensonal tensors.
     // Note: If the tensor is sparse, you must specify this value.
     repeated uint64 shape = 3 [packed = true];
 }
```

### Minimal repo / logs
- **Exact command to reproduce**:
```python3
import json, glob
import pyspark.sql.functions as F
from pyspark.ml.linalg import Vectors, VectorUDT, Vector, Matrices, MatrixUDT
from sagemaker.amazon.common import read_records
import sagemaker_pyspark
from pyspark.sql import SparkSession

classpath = ":".join(sagemaker_pyspark.classpath_jars())
spark = SparkSession.builder.config("spark.driver.extraClassPath", classpath).getOrCreate()

with open('json', 'w') as f:
    f.write(json.dumps({
        "c1":[1,2],
        "c2":[3,4],
    }))
    f.write('\n')
    f.write(json.dumps({
        "c1":[5,6],
        "c2":[7,8],
    }))
    f.write('\n')
df = spark.read.json('json')

# this is okay
sm = df.select(F.udf(lambda *args: Vectors.dense([float(x) for arr in args for x in arr]),
                     VectorUDT())
                    ('c1','c2')
              .alias('features')
             )
sm.write.format('sagemaker').save('spark.io', mode='overwrite')
with open(glob.glob('spark.io/part-*')[0], 'rb') as f:
    print(read_records(f))
[features {
  key: "values"
  value {
    float32_tensor {
      values: 1.0
      values: 2.0
      values: 3.0
      values: 4.0
    }
  }
}
, features {
  key: "values"
  value {
    float32_tensor {
      values: 5.0
      values: 6.0
      values: 7.0
      values: 8.0
    }
  }
}
]

# this is not okay
sm = df.select(F.udf(lambda *args: Matrices.dense(len(args), len(args[0]),
                                                  [x for arr in args for x in arr]),
                     MatrixUDT())
                    ('c1', 'c2')
              .alias('features')
             )
sm.write.format('sagemaker').save('spark.io', mode='overwrite')

# error message: java.lang.ClassCastException: org.apache.spark.ml.linalg.DenseMatrix cannot be cast to org.apache.spark.ml.linalg.Vector
```

**Comment by andremoeller** [comment]
Hi @yifeim ,

We should be able to encode both dense and sparse matrices in SageMaker's recordio protobuf format by changing this logic to work on SparseMatrix and DenseMatrix:

https://github.com/aws/sagemaker-spark/blob/master/sagemaker-spark-sdk/src/main/scala/com/amazonaws/services/sagemaker/sparksdk/protobuf/ProtobufConverter.scala#L68

https://github.com/aws/sagemaker-spark/blob/master/sagemaker-spark-sdk/src/main/scala/com/amazonaws/services/sagemaker/sparksdk/protobuf/ProtobufConverter.scala#L173-L190

I'll mark this down as a feature request, but I can't commit to when we'll be able to deliver this. If you need this feature and can send us a pull request, we can also work with you on getting it merged in. Thanks!

**Comment by yifeim** [comment]
@andremoeller Thanks for the pointers!  Will explore this option and sync up when there is progress. Please also let me know if there are similar feature requests and other special considerations. Seems like a good addition.

**Comment by yifeim** [comment]
Propose to close out the ticket since the request has been fulfilled. Many thanks everyone - especially @juliodelgadoaws
