### ISSUE TITLE
Internal architecture for a SageMaker Spark training job

### ISSUE THREAD

**Issue by imujjwal96** [aws/sagemaker-spark#86]
### Describe the problem

The example here:
https://github.com/aws/sagemaker-spark/tree/master/examples/notebooks/jupyter/xgboost
is for using Single machine and distributed training on Spark for multiclass classification with Amazon SageMaker XGBoost algorithm

How is this distributed environment provisioned for training? Does it launch multiple docker containers in the Master-Slave architecture with Spark functionality inside the single instance?

If we get a Spark environment for training, can we deploy own algorithm code with Spark and SparkSQL, and if so, can we access an external Hive metastore inside training?

**Comment by andremoeller** [comment]
Hey @imujjwal96 ,

> How is this distributed environment provisioned for training? Does it launch multiple docker containers in the Master-Slave architecture with Spark functionality inside the single instance?



The code in the notebook  creates a training job is made that runs SageMaker's XGBoost algorithm just as it would if the job were started by boto3, the AWS Java SDK, or any other SDK. However, the training job itself doesn't set up a Spark cluster -- this Spark SDK runs on a Spark cluster, and makes API calls to SageMaker.

`If we get a Spark environment for training, can we deploy own algorithm code with Spark and SparkSQL, and if so, can we access an external Hive metastore inside training?

It's possible to create a Docker container with a Spark environment that runs your own algorithm code, and you would be able to access external resources as you normally would outside of a SageMaker training job. SageMaker doesn't currently provide a Spark environment similar to our other offerings (MXNet, TensorFlow, Chainer, Scikit-Learn, PyTorch), creating a Docker container that sets up the distributed training environment is always an option.

I'm closing this issue, but please re-open it if you have more questions or if there's something I didn't address -- thanks!
