### ISSUE TITLE
Hyperparameter tuning with continues range of values.

### ISSUE THREAD

**Issue by sajjap** [aws/sagemaker-spark#89]
System Information
- **Spark**:
- **sagemaker-spark-sdk Version**:
- **Spark Version -spark_2.2.0-1.1.0**:
- **Algorithm (XGBoost)**:

### Describe the problem
How can we perform a Hyperparameter tuning the way we do it on a sagemaker notebook instance, by passing in the continues range of values, for eg.,
hyperparameter_ranges = {
    'alpha': ContinuousParameter(0.01, 10, scaling_type="Logarithmic"),
    'lambda': ContinuousParameter(0.01, 10, scaling_type="Logarithmic")
}

**Comment by knakad** [comment]
Hi there!

Can you provide a link to your current method of doing it? Either an example notebook instance or some sample code would be much appreciate =)

**Comment by sajjap** [comment]
@knakad ,
Here is the sample you could look at,
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/hyperparameter_tuning/xgboost_random_log/hpo_xgboost_random_log.ipynb

**Comment by ChoiByungWook** [comment]
Hello @sajjap,

As of now, hyper parameter tuning through the SageMaker spark SDK isn't supported. There may be some workarounds by utilizing the AWS SDK, however it may be difficult to integrate with native Spark and its features.

Apologies for the inconvenience.

As of now, I believe the SageMaker Python SDK is the only native solution for utilizing hyper parameter tuning.

**Comment by ChoiByungWook** [comment]
Closing in favor of: https://github.com/aws/sagemaker-spark/issues/55
