### ISSUE TITLE
The EMR Cluster Security group allows TCP port 8998 on the SageMaker Notebook Security group to ingress

### ISSUE THREAD

**Issue by yifeim** [aws/sagemaker-spark#9]
Hi,

I was trying to connect a sagemaker notebook instance to talk to EMR head node. It appears, however, that the notebook instance does not have a public ip address. I have `default` security group on both EMR and sagemaker. Still, I was not able to ping any nodes in my vpc from the terminal in the sagemaker jupyter notebook. Maybe I was missing something?

PS: starting sparkmagic with emr-5.8.0 results in bootstrap errors. I was able to start it with emr-5.10.0.

Thanks,
Yifei

**Comment by iquintero** [comment]
Hi @yifeim 

Thanks for your interest in SageMaker Spark! Here are the things to double check:

- Is your Notebook instance running in a VPC? If so, is it the same VPC as the EMR Cluster?
- Usually security groups have full network access to anything that shares the same security group. If that is the case you should be able to ping via the terminal on the notebook.  Was this removed?

**Comment by yifeim** [comment]
Hi,

Yes, the notebook was running in a subnet that belongs to the same vpc.

The `default` security group is enabled on both the notebook and the cluster (as additional security group). This group takes itself as source ip for all traffic and is registered in the same vpc.

I was not able to ping anything (my other ec2 machines etc) from the notebook terminal (which is an instance in the notebook machine). Is it expected that I should at least ping my other ec2 machines from notebook?

Thanks,
Yifei

**Comment by yifeim** [comment]
@iquintero Ignacio Quintero Thanks for looking into the matter, btw!

**Comment by iquintero** [comment]
You're welcome @yifeim  I think the best course of action is for you to create a post in the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=285&start=0) where our notebook team should be able to assist in troubleshooting this issue :)

**Comment by yifeim** [comment]
I was referred here when checking on the AWS Forum in the first place. I will continue on the other thread https://forums.aws.amazon.com/post!reply.jspa?messageID=816773 . I supposed you would have more experience because you must have made it through at some point. 

The aws forum also mentioned that notebooks cannot utilize VPC while training. Not sure if this is related. https://forums.aws.amazon.com/thread.jspa?threadID=269165&tstart=0

Will let you know if I make any progress.

**Comment by winstonaws** [comment]
@yifeim The first link doesn't seem to work for me - can you re-link to the forums thread?

**Comment by yifeim** [comment]
@winstonaws Sorry about that. I actually found the solution here: https://aws.amazon.com/blogs/ai/build-amazon-sagemaker-notebooks-backed-by-spark-in-amazon-emr/ 

The main issue I missed was that I should have used Private IP of EMR master. The blogpost also suggested Livy that I did not use at the earlier attempt.

**Comment by yangaws** [comment]
@yifeim Seems your problem is solved. I am going to close it. 

Feel free to reply this issue if you have further problems or questions.
